import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { after, before, test } from 'node:test';
import { startPreviewServer, type PreviewServer } from './preview-server';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

let preview: PreviewServer;

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function getPrimaryNav(html: string): string {
  const nav = html.match(/<nav[^>]*aria-label="Primary"[^>]*>[\s\S]*?<\/nav>/i)?.[0];
  assert.ok(nav, 'Primary nav was not rendered.');
  return nav;
}

function assertLink(navHtml: string, href: string, label: string) {
  const pattern = new RegExp(
    `<a(?=[^>]*href="${escapeRegExp(href)}")[^>]*>[\\s\\S]*?${escapeRegExp(label)}[\\s\\S]*?<\\/a>`,
    'i'
  );
  assert.match(navHtml, pattern, `Missing nav link ${label} -> ${href}`);
}

function assertActiveLink(navHtml: string, href: string, label: string) {
  const pattern = new RegExp(
    `<a(?=[^>]*href="${escapeRegExp(href)}")(?=[^>]*class="[^"]*\\bactive\\b[^"]*")[^>]*>[\\s\\S]*?${escapeRegExp(
      label
    )}[\\s\\S]*?<\\/a>`,
    'i'
  );
  assert.match(navHtml, pattern, `Expected ${href} to be active for ${label}.`);
}

function assertInactiveLink(navHtml: string, href: string, label: string) {
  const pattern = new RegExp(
    `<a(?=[^>]*href="${escapeRegExp(href)}")(?=[^>]*class="[^"]*\\bactive\\b[^"]*")[^>]*>[\\s\\S]*?${escapeRegExp(
      label
    )}[\\s\\S]*?<\\/a>`,
    'i'
  );
  assert.doesNotMatch(navHtml, pattern, `Did not expect ${href} to be active for ${label}.`);
}

function assertLabelOrder(navHtml: string, labels: string[]) {
  let previousIndex = -1;
  for (const label of labels) {
    const index = navHtml.indexOf(label);
    assert.notEqual(index, -1, `Expected to find ${label} in primary nav.`);
    if (previousIndex !== -1) {
      assert.ok(previousIndex < index, `Expected ${label} after previous primary nav item.`);
    }
    previousIndex = index;
  }
}

before(async () => {
  preview = await startPreviewServer();
});

after(async () => {
  await preview.close();
});

test('/blog and /changelog are browsable canonical index pages', async () => {
  const blogResponse = await fetch(`${preview.baseUrl}/blog`);
  assert.equal(blogResponse.status, 200);
  const blogHtml = await blogResponse.text();
  assert.match(blogHtml, /<h1[^>]*>\s*Blog\s*<\/h1>/);
  assert.match(blogHtml, /class="collection-feed[\s"]/);
  assert.match(blogHtml, /class="collection-feed-item[\s"]/);
  assert.match(blogHtml, /class="collection-tag[\s"]/);

  const changelogResponse = await fetch(`${preview.baseUrl}/changelog`);
  assert.equal(changelogResponse.status, 200);
  const changelogHtml = await changelogResponse.text();
  assert.match(changelogHtml, /<h1[^>]*>\s*Changelog\s*<\/h1>/);
  assert.match(changelogHtml, /class="collection-feed[\s"]/);
  assert.match(changelogHtml, /class="collection-feed-item[\s"]/);
});

test('blog and changelog detail pages include top and bottom canonical back links', async () => {
  const blogResponse = await fetch(`${preview.baseUrl}/blog/technical/i-must-scream`);
  assert.equal(blogResponse.status, 200);
  const blogHtml = await blogResponse.text();
  const blogBackLinks = blogHtml.match(/href="\/blog">← Back to Blog<\/a>/g) ?? [];
  assert.equal(blogBackLinks.length, 2, 'Expected top and bottom blog back links.');

  const changelogResponse = await fetch(`${preview.baseUrl}/changelog/changelogs/january-2026`);
  assert.equal(changelogResponse.status, 200);
  const changelogHtml = await changelogResponse.text();
  const changelogBackLinks =
    changelogHtml.match(/href="\/changelog">← Back to Changelog<\/a>/g) ?? [];
  assert.equal(changelogBackLinks.length, 1, 'Expected a changelog back link.');
});

test('llms endpoints remain available', async () => {
  // Generated by the starlight-llms-txt plugin (Starport Phase 6, ADR 0004 §4),
  // which superseded the hand-rolled src/pages/llms*.txt.ts endpoints. The index
  // links the abridged/complete sets and the reconciled non-docs optionalLinks;
  // llms-full.txt carries the full docs content behind a <SYSTEM> preamble.
  const llms = await fetch(`${preview.baseUrl}/llms.txt`);
  assert.equal(llms.status, 200);
  const llmsBody = await llms.text();
  assert.match(llmsBody, /# Promptless/i);
  assert.match(llmsBody, /\/llms-full\.txt/i);
  assert.match(llmsBody, /\/llms-small\.txt/i);
  assert.match(llmsBody, /\/blog/i);
  assert.match(llmsBody, /\/changelog/i);

  const llmsFull = await fetch(`${preview.baseUrl}/llms-full.txt`);
  assert.equal(llmsFull.status, 200);
  const llmsFullBody = await llmsFull.text();
  assert.match(llmsFullBody, /<SYSTEM>/i);
  assert.match(llmsFullBody, /Promptless/i);

  const llmsSmall = await fetch(`${preview.baseUrl}/llms-small.txt`);
  assert.equal(llmsSmall.status, 200);
  const llmsSmallBody = await llmsSmall.text();
  assert.match(llmsSmallBody, /Promptless/i);
});

test('homepage and docs pages include the llms.txt directive in html', async () => {
  const homepage = await fetch(`${preview.baseUrl}/`);
  assert.equal(homepage.status, 200);
  assert.match(await homepage.text(), /href="\/llms\.txt"[^>]*>llms\.txt<\/a>/i);

  const docsPage = await fetch(`${preview.baseUrl}/docs/start-here/welcome`);
  assert.equal(docsPage.status, 200);
  assert.match(await docsPage.text(), /href="\/llms\.txt"[^>]*>llms\.txt<\/a>/i);
});

test('website and docs pages render in permanent dark mode', async () => {
  for (const route of ['/', '/docs/start-here/welcome']) {
    const response = await fetch(`${preview.baseUrl}${route}`);
    assert.equal(response.status, 200);
    const html = await response.text();

    assert.match(html, /<html[^>]*data-theme="dark"/i);
    assert.match(html, /localStorage\.setItem\('starlight-theme', 'dark'\)/);
    assert.doesNotMatch(html, /<starlight-theme-select\b/i);
  }
});

test('primary nav keeps canonical routes with free tools tab', async () => {
  const response = await fetch(`${preview.baseUrl}/docs/start-here/welcome`);
  assert.equal(response.status, 200);
  const html = await response.text();
  const nav = getPrimaryNav(html);

  assertLink(nav, '/', 'Home');
  assertLink(nav, '/pricing', 'Pricing');
  assertLink(nav, '/docs', 'Docs');
  assertLink(nav, '/blog', 'Blog');
  assertLink(nav, '/changelog', 'Changelog');
  assertLink(nav, '/free-tools', 'Free tools');

  assertLabelOrder(nav, ['Home', 'Pricing', 'Docs', 'Blog', 'Changelog', 'Free tools']);
  assert.doesNotMatch(nav, /href="\/blog\/all"/);
  assert.doesNotMatch(nav, /href="\/changelog\/all"/);
});

test('website/docs/blog/changelog/free tools active state is correct', async () => {
  const websiteHtml = await (await fetch(`${preview.baseUrl}/`)).text();
  const websitePricingHtml = await (await fetch(`${preview.baseUrl}/pricing`)).text();
  const meetHtml = await (await fetch(`${preview.baseUrl}/meet`)).text();
  const docsHtml = await (await fetch(`${preview.baseUrl}/docs/start-here/welcome`)).text();
  const blogHtml = await (await fetch(`${preview.baseUrl}/blog`)).text();
  const changelogHtml = await (await fetch(`${preview.baseUrl}/changelog`)).text();
  const freeToolsIndexHtml = await (await fetch(`${preview.baseUrl}/free-tools`)).text();
  const freeToolsToolHtml = await (await fetch(`${preview.baseUrl}/free-tools/broken-link-report`)).text();

  const websiteNav = getPrimaryNav(websiteHtml);
  assertActiveLink(websiteNav, '/', 'Home');
  assertInactiveLink(websiteNav, '/docs', 'Docs');
  assertInactiveLink(websiteNav, '/blog', 'Blog');
  assertInactiveLink(websiteNav, '/changelog', 'Changelog');
  assertInactiveLink(websiteNav, '/free-tools', 'Free tools');

  const pricingNav = getPrimaryNav(websitePricingHtml);
  assertActiveLink(pricingNav, '/pricing', 'Pricing');
  assertInactiveLink(pricingNav, '/', 'Home');

  const meetNav = getPrimaryNav(meetHtml);
  assertInactiveLink(meetNav, '/', 'Home');

  const docsNav = getPrimaryNav(docsHtml);
  assertActiveLink(docsNav, '/docs', 'Docs');
  assertInactiveLink(docsNav, '/', 'Home');
  assertInactiveLink(docsNav, '/blog', 'Blog');
  assertInactiveLink(docsNav, '/changelog', 'Changelog');
  assertInactiveLink(docsNav, '/free-tools', 'Free tools');

  const blogNav = getPrimaryNav(blogHtml);
  assertActiveLink(blogNav, '/blog', 'Blog');
  assertInactiveLink(blogNav, '/', 'Home');
  assertInactiveLink(blogNav, '/docs', 'Docs');
  assertInactiveLink(blogNav, '/changelog', 'Changelog');
  assertInactiveLink(blogNav, '/free-tools', 'Free tools');

  const changelogNav = getPrimaryNav(changelogHtml);
  assertActiveLink(changelogNav, '/changelog', 'Changelog');
  assertInactiveLink(changelogNav, '/', 'Home');
  assertInactiveLink(changelogNav, '/docs', 'Docs');
  assertInactiveLink(changelogNav, '/blog', 'Blog');
  assertInactiveLink(changelogNav, '/free-tools', 'Free tools');

  const freeToolsIndexNav = getPrimaryNav(freeToolsIndexHtml);
  assertActiveLink(freeToolsIndexNav, '/free-tools', 'Free tools');
  assertInactiveLink(freeToolsIndexNav, '/', 'Home');
  assertInactiveLink(freeToolsIndexNav, '/docs', 'Docs');
  assertInactiveLink(freeToolsIndexNav, '/blog', 'Blog');
  assertInactiveLink(freeToolsIndexNav, '/changelog', 'Changelog');

  const freeToolsToolNav = getPrimaryNav(freeToolsToolHtml);
  assertActiveLink(freeToolsToolNav, '/free-tools', 'Free tools');
  assertInactiveLink(freeToolsToolNav, '/', 'Home');
  assertInactiveLink(freeToolsToolNav, '/docs', 'Docs');
  assertInactiveLink(freeToolsToolNav, '/blog', 'Blog');
  assertInactiveLink(freeToolsToolNav, '/changelog', 'Changelog');
});

test('/blog/all and /changelog/all remain compatibility redirects', async () => {
  const blogAll = await fetch(`${preview.baseUrl}/blog/all`, { redirect: 'manual' });
  if (blogAll.status >= 300 && blogAll.status < 400) {
    assert.equal(blogAll.headers.get('location'), '/blog');
  } else {
    assert.equal(blogAll.status, 200);
    const body = await blogAll.text();
    assert.match(body, /Redirecting to: \/blog/);
  }

  const changelogAll = await fetch(`${preview.baseUrl}/changelog/all`, { redirect: 'manual' });
  if (changelogAll.status >= 300 && changelogAll.status < 400) {
    assert.equal(changelogAll.headers.get('location'), '/changelog');
  } else {
    assert.equal(changelogAll.status, 200);
    const body = await changelogAll.text();
    assert.match(body, /Redirecting to: \/changelog/);
  }
});

test('website routes are canonicalized to /, /meet, and /pricing', async () => {
  const homepage = await fetch(`${preview.baseUrl}/`);
  assert.equal(homepage.status, 200);
  const homepageHtml = await homepage.text();
  assert.match(homepageHtml, /pl-site-page/);
  assert.match(homepageHtml, /How Promptless works/);

  const homeAlias = await fetch(`${preview.baseUrl}/home`, { redirect: 'manual' });
  if (homeAlias.status >= 300 && homeAlias.status < 400) {
    assert.equal(homeAlias.headers.get('location'), '/');
  } else {
    assert.equal(homeAlias.status, 200);
    assert.match(await homeAlias.text(), /Redirecting to: \//);
  }

  const demo = await fetch(`${preview.baseUrl}/demo`);
  assert.equal(demo.status, 200);
  // /demo is now a client-side redirect page to /#demo
  assert.match(await demo.text(), /\/#demo/);

  const meet = await fetch(`${preview.baseUrl}/meet`);
  assert.equal(meet.status, 200);
  assert.match(await meet.text(), /cal-inline-demo-booking/);

  const pricing = await fetch(`${preview.baseUrl}/pricing`);
  assert.equal(pricing.status, 200);
  assert.match(await pricing.text(), /Pricing/);

  // Alias → canonical destination (see the `redirects` map in astro.config.mjs;
  // /api-reference points at the API reference, not the homepage).
  const aliases: Record<string, string> = { '/use-cases': '/', '/faq': '/', '/api-reference': '/api/' };
  for (const [alias, destination] of Object.entries(aliases)) {
    const aliasResponse = await fetch(`${preview.baseUrl}${alias}`, { redirect: 'manual' });
    if (aliasResponse.status >= 300 && aliasResponse.status < 400) {
      assert.equal(aliasResponse.headers.get('location'), destination, `Alias ${alias}`);
      continue;
    }
    assert.equal(aliasResponse.status, 200);
    const body = await aliasResponse.text();
    assert.match(body, new RegExp(`Redirecting to: ${escapeRegExp(destination)}`), `Alias ${alias}`);
  }
});

test('homepage, meet, and pricing render website content', async () => {
  const homeResponse = await fetch(`${preview.baseUrl}/`);
  assert.equal(homeResponse.status, 200);
  const homeHtml = await homeResponse.text();
  assert.match(homeHtml, /pl-site-page/);
  // Product switcher (ProductSwitcher.astro): an accessible tablist of two pills
  // rendered above the hero. Both pills and both hero panels are server-rendered,
  // so we assert the full structure and copy of both.
  assert.match(homeHtml, /role="tablist"/);
  assert.match(homeHtml, /for customer-facing docs/);
  assert.match(homeHtml, /for agent instructions/);
  // Default tab (ProductSwitcher.astro): the "for agent instructions" pill is now
  // the default-selected tab, and "for customer-facing docs" is not. Use lookahead
  // regexes so raw HTML attribute order can vary — we only require the pill's id and
  // aria-selected to co-occur in the same opening tag.
  assert.match(
    homeHtml,
    /<button(?=[^>]*id="pl-product-switcher-tab-agents")(?=[^>]*aria-selected="true")[^>]*>/
  );
  assert.doesNotMatch(
    homeHtml,
    /<button(?=[^>]*id="pl-product-switcher-tab-docs")(?=[^>]*aria-selected="true")[^>]*>/
  );
  // Docs panel (HeroV2.astro, id=pl-hero-panel-docs, now hidden by default but in the DOM).
  assert.match(homeHtml, /id="pl-hero-panel-docs"/);
  // The docs panel carries the `hidden` attribute; the agents panel does not.
  assert.match(homeHtml, /<div(?=[^>]*id="pl-hero-panel-docs")(?=[^>]*\shidden)[^>]*>/);
  assert.doesNotMatch(homeHtml, /<div(?=[^>]*id="pl-hero-panel-agents")(?=[^>]*\shidden)[^>]*>/);
  // Below-fold docs-only slot (home.mdx: <div id="pl-below-fold-docs" hidden>) wraps
  // the 1.0 demo video. It ships server-rendered `hidden` because the agents pill is
  // the default-active tab; it is revealed client-side whenever the docs pill becomes
  // active, whether by auto-rotate or an explicit click (ProductSwitcher.astro
  // syncTabSlots()). Fetch-only smoke tests never run that JS, so we can only assert
  // the default server state, which is `hidden`. Lookahead regex keeps us agnostic to
  // raw HTML attribute ordering.
  assert.match(homeHtml, /<div(?=[^>]*id="pl-below-fold-docs")(?=[^>]*\shidden)[^>]*>/);
  // Below-fold agents-only slot (home.mdx: <div id="pl-below-fold-agents">) wraps the
  // expanded agent-governance story. It is the mirror image of the docs slot: because the
  // agents pill is the default-active tab, this slot ships server-rendered with no
  // `hidden` attribute, and is hidden client-side whenever the docs pill is the active
  // one, by auto-rotate or click (ProductSwitcher.astro syncTabSlots()). Fetch-only
  // smoke tests never run that JS, so we assert the default server state, which has no
  // `hidden` attribute. Lookahead regex keeps us agnostic to raw HTML attribute ordering.
  assert.doesNotMatch(homeHtml, /<div(?=[^>]*id="pl-below-fold-agents")(?=[^>]*\shidden)[^>]*>/);
  // Per-tab hero asides (home.mdx: .pl-hero-v2-asides in the hero right column). They
  // follow the active pill exactly like the below-fold slots, so with agents as the
  // default tab the agents aside ships visible and the docs aside ships `hidden`.
  assert.match(homeHtml, /id="pl-hero-aside-agents"/);
  assert.doesNotMatch(homeHtml, /<div(?=[^>]*id="pl-hero-aside-agents")(?=[^>]*\shidden)[^>]*>/);
  assert.match(homeHtml, /id="pl-hero-aside-docs"/);
  assert.match(homeHtml, /<div(?=[^>]*id="pl-hero-aside-docs")(?=[^>]*\shidden)[^>]*>/);
  // The docs aside ships `hidden`, but its contents are still server-rendered (the
  // switcher only toggles the attribute, it never injects markup): the hero vertical
  // ticker, the mobile-only full carousel, and that carousel's heading. Assert the
  // `class="…` attribute rather than the bare class name so a stylesheet mentioning
  // the same selector can't satisfy these on its own. TestimonialsVertical.astro uses
  // scoped styles, so Astro appends a scope class — match the prefix, not a closed quote.
  assert.match(homeHtml, /class="pl-testimonials-vertical[\s"]/);
  assert.match(homeHtml, /class="pl-mobile-testimonials[\s"]/);
  assert.match(homeHtml, /Writers, developers, and founders all love Promptless/);
  // Two testimonial identities, asserted independently of each other. Order-independent
  // on purpose: the testimonials array is fixed today, but an open PR (#674) adds a
  // build-time Fisher-Yates shuffle to TestimonialsVertical.astro, so nothing here may
  // depend on order, adjacency, or a full quote string.
  assert.match(homeHtml, /Mo King/);
  assert.match(homeHtml, /Nicholas DeWald/);
  // Nesting lock: the stat cards must stay inside #pl-hero-aside-agents and the vertical
  // ticker inside #pl-hero-aside-docs, so a refactor cannot re-orphan either from the tab
  // machinery (the #776 regression that put the agent stats on both tabs). Index
  // comparison against the aside wrappers rather than exact markup, so intervening
  // attributes or wrappers stay allowed.
  // Match on the `class="…` prefix, not the bare class name, so a bundled or inlined
  // stylesheet mentioning the same selector can't satisfy the index comparison. The
  // prefix (rather than a closed quote) tolerates Astro's appended scope class.
  const agentsAsideIndex = homeHtml.indexOf('id="pl-hero-aside-agents"');
  const docsAsideIndex = homeHtml.indexOf('id="pl-hero-aside-docs"');
  const statCardsIndex = homeHtml.indexOf('class="pl-stat-cards');
  const verticalTestimonialsIndex = homeHtml.indexOf('class="pl-testimonials-vertical');
  assert.ok(
    agentsAsideIndex !== -1 && statCardsIndex > agentsAsideIndex && statCardsIndex < docsAsideIndex,
    'Expected .pl-stat-cards to render inside #pl-hero-aside-agents, before #pl-hero-aside-docs.'
  );
  assert.ok(
    docsAsideIndex !== -1 && verticalTestimonialsIndex > docsAsideIndex,
    'Expected .pl-testimonials-vertical to render inside #pl-hero-aside-docs.'
  );
  // The agent story renders a complete narrative, rather than only the flywheel.
  assert.match(homeHtml, /Secure, on‑prem by default/);
  assert.match(homeHtml, /White-glove onboarding/);
  assert.match(homeHtml, /From DevOps to marketing/);
  assert.match(homeHtml, /Stop making your AI workforce relearn what your team already knows\./);
  assert.match(homeHtml, /See the work your agents keep making humans redo\./);
  assert.match(homeHtml, /Turn the best correction into a team-wide standard\./);
  assert.match(homeHtml, /Make one person’s breakthrough show up in every relevant session\./);
  assert.match(homeHtml, /Every session feeds the next improvement\./);
  assert.match(homeHtml, /virtuous-cycle-flywheel\.svg/);
  assert.match(homeHtml, /Make your best work the team’s new default\./);
  assert.match(homeHtml, /Improve the fleet without giving up control\./);
  assert.match(homeHtml, /Questions, answered\./);
  assert.match(homeHtml, /See what your agent traces are already trying to teach you\./);
  assert.doesNotMatch(homeHtml, /Illustrative fleet-wide impact/);
  assert.match(homeHtml, /Instruction debt report/);
  assert.match(homeHtml, /Proposed fleet upgrades/);
  assert.match(homeHtml, /Before vs\. governed/);
  assert.match(homeHtml, /12\.8M/);
  assert.match(homeHtml, /\$24K/);
  assert.match(homeHtml, /What counts as an agent instruction\?/);
  assert.match(homeHtml, /data-track-location="agent_governance_footer"/);
  for (const section of [
    'agent-differentiation',
    'agent-impact-examples',
    'agent-learning-loop',
    'agent-use-cases',
    'agent-governance',
    'agent-faq',
    'agent-final-cta',
  ]) {
    assert.match(homeHtml, new RegExp(`data-section-tracked="${section}"`));
  }
  // The 30-day impact stat block (home.mdx, inside
  // #pl-hero-aside-agents in the hero right column's .pl-hero-v2-asides stack). That
  // aside ships server-rendered visible because agents is the default tab, so the
  // heading and the four stat figures are present in the fetched HTML. The
  // The proof block reinforces the time, token, and dollar outcomes.
  assert.match(homeHtml, /Typical improvements after 30 days/);
  assert.match(homeHtml, /42%/);
  assert.match(homeHtml, /15%/);
  assert.match(homeHtml, /32%/);
  assert.match(homeHtml, /18%/);
  assert.match(homeHtml, /decrease in token spend/);
  assert.match(homeHtml, /increase in first-attempt completion/);
  assert.doesNotMatch(homeHtml, /dogfood/i);
  // The 1.0 demo video is KEPT (wrapped, not removed). VideoEmbed.astro extracts the
  // YouTube id from the embed URL and renders LiteYouTube, whose server-rendered facade
  // marks the container with data-video-id (LiteYouTube.astro). Assert that marker for
  // the demo video id so a regression that drops the video is caught.
  assert.match(homeHtml, /data-video-id="AONpRsZJkTY"/);
  assert.match(homeHtml, /Write the docs\./);
  assert.match(homeHtml, /Skip the busywork\./);
  assert.match(homeHtml, /Promptless suggests doc updates when your product changes\./);
  // Agents panel (HeroV2.astro, id=pl-hero-panel-agents, now default-visible).
  assert.match(homeHtml, /id="pl-hero-panel-agents"/);
  assert.match(homeHtml, /Promptless Instruction Governance/);
  assert.match(homeHtml, /Every agent trace should improve your entire AI workforce\./);
  // Subtitle contains an inline <code>AGENTS.md</code> tag; assert fragments around it
  // without depending on Astro's scoped attributes.
  assert.match(homeHtml, /automatically improves your team’s Skills, Subagents, Hooks,/);
  assert.match(homeHtml, /<code[^>]*>AGENTS\.md<\/code>/);
  assert.match(homeHtml, /with every session trace across your fleet/);
  assert.match(homeHtml, /Consistent, access-controlled skills across your teams/);
  assert.match(homeHtml, /Your traces are securely analyzed on your systems/);
  assert.match(homeHtml, /Works with all your agents/);
  // Lock the new agents-panel logo strip that follows the third bullet.
  assert.match(homeHtml, /pl-hero-v2-toolchain-agents/);
  assert.match(homeHtml, /alt="Gemini CLI"/);
  assert.match(homeHtml, /How Promptless works/);
  assert.match(homeHtml, /Get a demo/);
  assert.match(homeHtml, /Ask your favorite AI about Promptless/);
  assert.match(homeHtml, /data-track-action="ask_ai"/);
  assert.match(homeHtml, /data-track-location="homepage_ask_ai"/);
  assert.doesNotMatch(homeHtml, /Getting Started/i);
  // Guard against the removed #776 "two cards" / TwoTracks positioning creeping back.
  assert.doesNotMatch(homeHtml, /Promptless keeps it correct/);
  assert.doesNotMatch(homeHtml, /Promptless for Docs/);
  assert.doesNotMatch(homeHtml, /Coming soon/i);
  // Guard against the pre-reword agents-panel copy silently returning.
  assert.doesNotMatch(homeHtml, /governed documentation/);
  assert.doesNotMatch(homeHtml, /control plane/);
  assert.doesNotMatch(homeHtml, /Surfaces stale, missing, or contradictory/);
  assert.doesNotMatch(homeHtml, /Give your AI workforce superpowers/);

  const meetResponse = await fetch(`${preview.baseUrl}/meet`);
  assert.equal(meetResponse.status, 200);
  const meetHtml = await meetResponse.text();
  assert.match(meetHtml, /Book a 15-minute demo/);
  assert.match(meetHtml, /cal-inline-demo-booking/);

  const pricingResponse = await fetch(`${preview.baseUrl}/pricing`);
  assert.equal(pricingResponse.status, 200);
  const pricingHtml = await pricingResponse.text();
  assert.match(pricingHtml, /Pricing/);
  assert.match(pricingHtml, /Startup/);
  assert.match(pricingHtml, /Growth/);
  assert.match(pricingHtml, /Enterprise/);
  // New two-tab pricing switcher (PricingCards.astro) mirroring the homepage. Both
  // pricing panels are server-rendered, so the switcher and the agent-instructions
  // content are present in the fetched HTML regardless of the default tab.
  assert.match(pricingHtml, /role="tablist"/);
  assert.match(pricingHtml, /for agent instructions/);
  assert.match(pricingHtml, /for customer-facing docs/);
  // Default tab (PricingCards.astro): the docs pill is now the default-selected tab
  // and the agents pill is not; correspondingly the agents panel carries `hidden`
  // and the docs panel does not. DOM order of pills/panels is unchanged. Lookahead
  // regexes keep us agnostic to raw HTML attribute ordering.
  assert.match(
    pricingHtml,
    /<button(?=[^>]*id="pl-pricing-tab-docs")(?=[^>]*aria-selected="true")[^>]*>/
  );
  assert.doesNotMatch(
    pricingHtml,
    /<button(?=[^>]*id="pl-pricing-tab-agents")(?=[^>]*aria-selected="true")[^>]*>/
  );
  assert.match(pricingHtml, /<div(?=[^>]*id="pl-pricing-panel-agents")(?=[^>]*\shidden)[^>]*>/);
  assert.doesNotMatch(pricingHtml, /<div(?=[^>]*id="pl-pricing-panel-docs")(?=[^>]*\shidden)[^>]*>/);
  // Agent-instructions pricing view: "Contact us" price, usage boundaries, footnote,
  // and distinctive feature bullets — all strings that do not collide with docs-side copy.
  assert.match(pricingHtml, /Contact us/);
  assert.match(pricingHtml, /Fewer than 50 agent instructions/);
  assert.match(pricingHtml, /50-200 agent instructions/);
  assert.match(pricingHtml, /More than 200 agent instructions/);
  assert.match(pricingHtml, /Agent instructions are skills, subagent/);
  assert.match(pricingHtml, /Centralized Instruction Hub/);
  assert.match(pricingHtml, /Native plugins for Claude Code and Codex/);
  // Docs-side pricing (server-rendered on the hidden docs panel) still holds in full.
  assert.match(pricingHtml, /\$500\s*\/\s*mo/);
  assert.match(pricingHtml, /All plans include a 14-day free trial\./);
  assert.match(pricingHtml, /Up to 200 Pages\*/);
  assert.match(pricingHtml, /Pages are normalized/);
  assert.match(pricingHtml, /name=\"growth_bundle\"/);
  assert.match(pricingHtml, /200-500 Pages\*/);
  assert.match(pricingHtml, /500-1,000 Pages\*/);
  assert.match(pricingHtml, /1,000-2,000 Pages\*/);
  assert.match(pricingHtml, /2,000-5,000 Pages\*/);
  assert.match(pricingHtml, /Slack \+ GitHub integrations/);
  assert.match(pricingHtml, /Open-source, non-commercial project\?/);
  assert.match(pricingHtml, /href=\"https:\/\/promptless\.ai\/docs\/start-here\/open-source-quickstart\"/);
  assert.match(pricingHtml, /Book demo/);
  assert.doesNotMatch(pricingHtml, /<h3>Compare plans<\/h3>/);
});

test('every same-origin docs link on the homepage resolves to a real page', async (t) => {
  // The smoke harness is the right layer for this. preview-server.ts replays the
  // Vercel redirect routes from .vercel/output/config.json as real 3xx responses
  // (loadRedirectRoutes), so an adapter build reproduces production's exact-match,
  // trailing-slash-sensitive redirect behavior. That is what the authored hero
  // hrefs tripped over: a redirect source without a trailing slash never matches
  // an href that has one. A static build carries no redirect routes at all
  // (resolveBuildOutput returns `redirects: []`), so the exact-match guarantee
  // holds only under the adapter build — see the stub note in resolveHref below.
  const homepage = await fetch(`${preview.baseUrl}/`);
  assert.equal(homepage.status, 200);
  const html = await homepage.text();

  const previewOrigin = new URL(preview.baseUrl).origin;
  const MAX_HOPS = 5;

  // Collect same-site docs hrefs in both authored forms: root-relative (/docs…)
  // and origin-prefixed (https://promptless.ai/docs…). Absolute hrefs are
  // normalized to their pathname so every request below goes to the preview
  // server — this test must never reach promptless.ai, or a link broken on this
  // branch would pass against production.
  const hrefs = new Set<string>();
  for (const [, value] of html.matchAll(/href="([^"]*)"/g)) {
    const isAbsolute = /^https:\/\/promptless\.ai\/docs(?:[/?#]|$)/.test(value);
    if (!isAbsolute && !/^\/docs(?:[/?#]|$)/.test(value)) continue;
    const pathname = isAbsolute ? new URL(value).pathname : value;
    hrefs.add(pathname.replace(/#.*$/, ''));
  }

  // Vacuity guard: a refactor that drops the hero must fail here instead of
  // passing an empty loop.
  assert.ok(
    hrefs.size >= 10,
    `Homepage rendered fewer docs links than expected (found ${hrefs.size}, expected at least 10).`
  );

  type Resolution =
    | { kind: 'final'; status: number; chain: string[] }
    | { kind: 'off-origin'; location: string; chain: string[] };

  async function resolveHref(href: string): Promise<Resolution> {
    const chain: string[] = [href];
    const visited = new Set<string>();
    let current = new URL(href, preview.baseUrl);
    let hops = 0;

    for (;;) {
      assert.ok(
        !visited.has(current.href),
        `Redirect loop for ${href} (chain: ${chain.join(' -> ')}).`
      );
      visited.add(current.href);
      assert.ok(
        hops <= MAX_HOPS,
        `${href} exceeded ${MAX_HOPS} redirect hops (chain: ${chain.join(' -> ')}).`
      );
      hops += 1;

      const response = await fetch(current, { redirect: 'manual' });

      if (response.status >= 300 && response.status < 400) {
        const location = response.headers.get('location');
        assert.ok(
          location,
          `${href} returned ${response.status} with no Location header (chain: ${chain.join(' -> ')}).`
        );
        const next = new URL(location, current);
        // loadRedirectRoutes replays each Vercel route without its `has`
        // conditions, so a host-conditional rule could in principle surface an
        // absolute production Location. Never fetch off-origin from a smoke test:
        // report it as unverifiable rather than asserting on production.
        if (next.origin !== previewOrigin) return { kind: 'off-origin', location: next.href, chain };
        chain.push(next.pathname);
        current = next;
        continue;
      }

      if (response.status === 200) {
        // Static builds (MCP_ENABLED=false → dist) have no platform redirects:
        // Astro emits a "Redirecting to: …" stub page with a 200 instead, as the
        // /blog/all and website-alias tests above allow for. Follow the stub so
        // the dist path keeps real coverage instead of accepting the stub itself.
        // The trade-off: on a trailing-slash mismatch the directory-level stub
        // answers 200 on its own, so following it cannot tell a correctly slashed
        // href from one that only resolves because the stub bridges the mismatch.
        // The exact-match assertion is therefore only real under the adapter
        // build, which is what CI's check.yml runs.
        const stubTarget = (await response.text()).match(/Redirecting to:\s*([^\s<"']+)/)?.[1];
        if (stubTarget) {
          const next = new URL(stubTarget, current);
          if (next.origin !== previewOrigin) return { kind: 'off-origin', location: next.href, chain };
          chain.push(next.pathname);
          current = next;
          continue;
        }
      }

      return { kind: 'final', status: response.status, chain };
    }
  }

  let verified = 0;
  for (const href of [...hrefs].sort()) {
    const resolution = await resolveHref(href);
    if (resolution.kind === 'off-origin') {
      t.diagnostic(
        `${href} redirects off-origin to ${resolution.location}; not locally verifiable (chain: ${resolution.chain.join(' -> ')}).`
      );
      continue;
    }
    assert.equal(
      resolution.status,
      200,
      `Homepage docs link ${href} resolved to ${resolution.status}, expected 200 (chain: ${resolution.chain.join(' -> ')}).`
    );
    verified += 1;
  }

  // Off-origin hops above are reported, not asserted on. This keeps that escape
  // hatch from turning the whole test into diagnostics-only coverage.
  assert.ok(
    verified >= 10,
    `Only ${verified} of ${hrefs.size} homepage docs links were verified against the preview server; expected at least 10.`
  );
});

test('website header replaces home search with the launch announcement', async () => {
  const homeResponse = await fetch(`${preview.baseUrl}/`);
  assert.equal(homeResponse.status, 200);
  const homeHtml = await homeResponse.text();
  assert.match(homeHtml, /href="https:\/\/app\.gopromptless\.ai"[^>]*>\s*Sign in/i);
  assert.match(homeHtml, /href="\/meet"[^>]*>\s*Get a demo/i);
  assert.match(homeHtml, /href="https:\/\/accounts\.gopromptless\.ai\/sign-up"[^>]*>\s*Start for free/i);
  assert.match(
    homeHtml,
    /href="\/blog\/product-updates\/introducing-promptless-for-agent-instructions"/i
  );
  assert.doesNotMatch(homeHtml, /aria-label="Search"/i);

  const docsResponse = await fetch(`${preview.baseUrl}/docs/start-here/welcome`);
  assert.equal(docsResponse.status, 200);
  assert.match(await docsResponse.text(), /aria-label="Search"/i);
});

test('legal pages render', async () => {
  const privacyResponse = await fetch(`${preview.baseUrl}/privacy`);
  assert.equal(privacyResponse.status, 200);
  const privacyHtml = await privacyResponse.text();
  assert.match(privacyHtml, /Privacy Policy/i);
  assert.match(privacyHtml, /help@gopromptless\.ai/i);

  const termsResponse = await fetch(`${preview.baseUrl}/terms`);
  assert.equal(termsResponse.status, 200);
  const termsHtml = await termsResponse.text();
  assert.match(termsHtml, /Terms of Use/i);
  assert.match(termsHtml, /hello@gopromptless\.ai/i);
});

test('free tool page renders form fields and explanatory copy', async () => {
  const indexResponse = await fetch(`${preview.baseUrl}/free-tools`);
  assert.equal(indexResponse.status, 200);
  const indexHtml = await indexResponse.text();
  assert.match(indexHtml, /Free tools/i);
  assert.match(indexHtml, /Broken Link Report/i);

  const response = await fetch(`${preview.baseUrl}/free-tools/broken-link-report`);
  assert.equal(response.status, 200);
  const html = await response.text();

  assert.match(html, /Broken Link Report/);
  assert.match(html, /Paste your site URL and email/i);
  assert.match(html, /name="url"/);
  assert.match(html, /name="email"/);
  assert.match(html, /Show advanced options/i);
  assert.match(html, /name="check_external"/);
  assert.match(html, /name="check_anchors"/);
  assert.match(html, /name="max_pages"/);
  assert.doesNotMatch(html, /name="concurrency"/);
  assert.doesNotMatch(html, /name="timeout_seconds"/);
  assert.match(html, /name="website"/);
  assert.match(html, /Send me the report/);

  assert.doesNotMatch(html, /data-website-sidebar="true"/);
});

test('website markdown endpoints are available for agent-friendly content', async () => {
  const routes = [
    { path: '/index.md', heading: /# Automatically update your docs/, detail: /## How Promptless works/ },
    { path: '/pricing.md', heading: /# Pricing that fits teams of all sizes/, detail: /## Startup/ },
    { path: '/free-tools.md', heading: /# Free tools/, detail: /## Broken Link Report/ },
    {
      path: '/free-tools/broken-link-report.md',
      heading: /# Broken Link Report/,
      detail: /## Advanced options/,
    },
  ];

  for (const route of routes) {
    const response = await fetch(`${preview.baseUrl}${route.path}`);
    assert.equal(response.status, 200, `Expected ${route.path} to be available.`);
    assert.match(
      response.headers.get('content-type') ?? '',
      /^text\/markdown\b/i,
      `Expected ${route.path} to return markdown.`
    );

    const body = await response.text();
    assert.match(body, route.heading, `Expected ${route.path} to include its markdown title.`);
    assert.match(body, route.detail, `Expected ${route.path} to include key agent-facing content.`);
  }

  // The pricing markdown mirror now also carries the agent-instructions section
  // (websiteMarkdown/pricing.md) alongside the unchanged docs-side plans.
  const pricingMd = await (await fetch(`${preview.baseUrl}/pricing.md`)).text();
  assert.match(pricingMd, /## For agent instructions/);
  assert.match(pricingMd, /Agent instructions are skills, subagent/);
});

test('website compatibility routes redirect to canonical destinations', async () => {
  // Alias → canonical destination (see the `redirects` map in astro.config.mjs).
  const rootAliases: Record<string, string> = {
    '/home': '/',
    '/use-cases': '/',
    '/faq': '/',
    '/api-reference': '/api/',
    '/page': '/',
    '/wtd': '/',
    '/hn': '/',
  };
  for (const [alias, destination] of Object.entries(rootAliases)) {
    const response = await fetch(`${preview.baseUrl}${alias}`, { redirect: 'manual' });
    if (response.status >= 300 && response.status < 400) {
      assert.equal(response.headers.get('location'), destination, `Alias ${alias}`);
      continue;
    }
    assert.equal(response.status, 200);
    const body = await response.text();
    assert.match(body, new RegExp(`Redirecting to: ${escapeRegExp(destination)}`), `Alias ${alias}`);
  }
});

test('adapter build wires the /mcp route to the render function (ADR 0007)', (t) => {
  // Only meaningful for adapter builds; MCP_ENABLED=false static builds have no
  // serverless function by design.
  const configPath = path.join(REPO_ROOT, '.vercel', 'output', 'config.json');
  if (!existsSync(configPath)) {
    t.skip('No .vercel/output/config.json — static (MCP_ENABLED=false) build.');
    return;
  }
  const config = JSON.parse(readFileSync(configPath, 'utf8')) as {
    routes?: Array<{ src?: string; dest?: string }>;
  };
  const mcpRoute = (config.routes ?? []).find(
    (route) => route.src && route.dest && new RegExp(route.src).test('/mcp')
  );
  assert.ok(mcpRoute, 'Expected a config.json route mapping /mcp to a function.');
  assert.ok(
    existsSync(path.join(REPO_ROOT, '.vercel', 'output', 'functions', `${mcpRoute.dest}.func`)),
    `Expected the ${mcpRoute.dest} serverless function to exist in the build output.`
  );
});
